FROM node:18-slim

# Install dependencies for Puppeteer / Chromium
RUN apt-get update \
    && apt-get install -y wget gnupg \
    && apt-get install -y libxss1 libnss3 libatk-bridge2.0-0 libgtk-3-0 libasound2 libgbm-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY whatsapp_service.js .
# Do not copy auth folder directly in dockerfile, it's better to mount it as a volume if needed, 
# or just let it generate a new one.

EXPOSE 3000

CMD ["node", "whatsapp_service.js"]
